from Morpion import Morpion

output = open("output.txt", "w+")
game = Morpion()
board = game.init_board()
output.write(f"1 board {board}\n")
board = game.get_board()
output.write(f"2 board {board}\n")
board = game.play_morpion(4)
output.write(f"3 board {board}\n")
board = game.get_board()
output.write(f"4 board {board}\n")
board = game.play_morpion(5)
output.write(f"5 board {board}\n")
board = game.get_board()
output.write(f"6 board {board}\n")
board = game.play_morpion(1)
output.write(f"7 board {board}\n")
board = game.get_board()
output.write(f"8 board {board}\n")
board = game.play_morpion(2)
output.write(f"9 board {board}\n")
board = game.get_board()
output.write(f"10 board {board}\n")
board = game.play_morpion(7)
output.write(f"11 board {board}\n")
output.close()